Namespace Models
    Public Class SampleData
        Public Shared Orders As New List(Of SampleOrder) From {
            New SampleOrder With {.OrderID = 10248, .OrderDate = New Date(1996, 7, 4), .ShipCountry = "France", .ShipCity = "Reims", .CustomerName = "Paul Henriot"},
            New SampleOrder With {.OrderID = 10249, .OrderDate = New Date(1996, 7, 5), .ShipCountry = "Germany", .ShipCity = "Münster", .CustomerName = "Karin Josephs"},
            New SampleOrder With {.OrderID = 10250, .OrderDate = New Date(1996, 7, 8), .ShipCountry = "Brazil", .ShipCity = "Rio de Janeiro", .CustomerName = "Mario Pontes"},
            New SampleOrder With {.OrderID = 10251, .OrderDate = New Date(1996, 7, 8), .ShipCountry = "France", .ShipCity = "Lyon", .CustomerName = "Mary Saveley"},
            New SampleOrder With {.OrderID = 10252, .OrderDate = New Date(1996, 7, 9), .ShipCountry = "Belgium", .ShipCity = "Charleroi", .CustomerName = "Pascale Cartrain"},
            New SampleOrder With {.OrderID = 10253, .OrderDate = New Date(1996, 7, 10), .ShipCountry = "Brazil", .ShipCity = "Rio de Janeiro", .CustomerName = "Mario Pontes"},
            New SampleOrder With {.OrderID = 10254, .OrderDate = New Date(1996, 7, 11), .ShipCountry = "Switzerland", .ShipCity = "Bern", .CustomerName = "Yang Wang"},
            New SampleOrder With {.OrderID = 10255, .OrderDate = New Date(1996, 7, 12), .ShipCountry = "Switzerland", .ShipCity = "Genève", .CustomerName = "Michael Holz"},
            New SampleOrder With {.OrderID = 10256, .OrderDate = New Date(1996, 7, 15), .ShipCountry = "Brazil", .ShipCity = "Resende", .CustomerName = "Paula Parente"},
            New SampleOrder With {.OrderID = 10257, .OrderDate = New Date(1996, 7, 16), .ShipCountry = "Venezuela", .ShipCity = "San Cristóbal", .CustomerName = "Carlos Hernández"},
            New SampleOrder With {.OrderID = 10258, .OrderDate = New Date(1996, 7, 17), .ShipCountry = "Austria", .ShipCity = "Graz", .CustomerName = "Roland Mendel"},
            New SampleOrder With {.OrderID = 10259, .OrderDate = New Date(1996, 7, 18), .ShipCountry = "Mexico", .ShipCity = "México D.F.", .CustomerName = "Francisco Chang"},
            New SampleOrder With {.OrderID = 10260, .OrderDate = New Date(1996, 7, 19), .ShipCountry = "Germany", .ShipCity = "Köln", .CustomerName = "Henriette Pfalzheim"},
            New SampleOrder With {.OrderID = 10261, .OrderDate = New Date(1996, 7, 19), .ShipCountry = "Brazil", .ShipCity = "Rio de Janeiro", .CustomerName = "Bernardo Batista"},
            New SampleOrder With {.OrderID = 10262, .OrderDate = New Date(1996, 7, 22), .ShipCountry = "USA", .ShipCity = "Albuquerque", .CustomerName = "Paula Wilson"},
            New SampleOrder With {.OrderID = 10263, .OrderDate = New Date(1996, 7, 23), .ShipCountry = "Austria", .ShipCity = "Graz", .CustomerName = "Roland Mendel"},
            New SampleOrder With {.OrderID = 10264, .OrderDate = New Date(1996, 7, 24), .ShipCountry = "Sweden", .ShipCity = "Bräcke", .CustomerName = "Maria Larsson"},
            New SampleOrder With {.OrderID = 10265, .OrderDate = New Date(1996, 7, 25), .ShipCountry = "France", .ShipCity = "Strasbourg", .CustomerName = "Frédérique Citeaux"},
            New SampleOrder With {.OrderID = 10266, .OrderDate = New Date(1996, 7, 26), .ShipCountry = "Finland", .ShipCity = "Oulu", .CustomerName = "Pirkko Koskitalo"},
            New SampleOrder With {.OrderID = 10267, .OrderDate = New Date(1996, 7, 29), .ShipCountry = "Germany", .ShipCity = "München", .CustomerName = "Peter Franken"},
            New SampleOrder With {.OrderID = 10268, .OrderDate = New Date(1996, 7, 30), .ShipCountry = "Venezuela", .ShipCity = "Caracas", .CustomerName = "Manuel Pereira"},
            New SampleOrder With {.OrderID = 10269, .OrderDate = New Date(1996, 7, 31), .ShipCountry = "USA", .ShipCity = "Seattle", .CustomerName = "Karl Jablonski"},
            New SampleOrder With {.OrderID = 10270, .OrderDate = New Date(1996, 8, 1), .ShipCountry = "Finland", .ShipCity = "Oulu", .CustomerName = "Pirkko Koskitalo"},
            New SampleOrder With {.OrderID = 10271, .OrderDate = New Date(1996, 8, 1), .ShipCountry = "USA", .ShipCity = "Lander", .CustomerName = "Art Braunschweiger"},
            New SampleOrder With {.OrderID = 10272, .OrderDate = New Date(1996, 8, 2), .ShipCountry = "USA", .ShipCity = "Albuquerque", .CustomerName = "Paula Wilson"},
            New SampleOrder With {.OrderID = 10273, .OrderDate = New Date(1996, 8, 5), .ShipCountry = "Germany", .ShipCity = "Cunewalde", .CustomerName = "Horst Kloss"},
            New SampleOrder With {.OrderID = 10274, .OrderDate = New Date(1996, 8, 6), .ShipCountry = "France", .ShipCity = "Reims", .CustomerName = "Paul Henriot"},
            New SampleOrder With {.OrderID = 10275, .OrderDate = New Date(1996, 8, 7), .ShipCountry = "Italy", .ShipCity = "Bergamo", .CustomerName = "Giovanni Rovelli"},
            New SampleOrder With {.OrderID = 10276, .OrderDate = New Date(1996, 8, 8), .ShipCountry = "Mexico", .ShipCity = "México D.F.", .CustomerName = "Miguel Angel Paolino"},
            New SampleOrder With {.OrderID = 10277, .OrderDate = New Date(1996, 8, 9), .ShipCountry = "Germany", .ShipCity = "Leipzig", .CustomerName = "Alexander Feuer"},
            New SampleOrder With {.OrderID = 10278, .OrderDate = New Date(1996, 8, 12), .ShipCountry = "Sweden", .ShipCity = "Luleå", .CustomerName = "Christina Berglund"},
            New SampleOrder With {.OrderID = 10279, .OrderDate = New Date(1996, 8, 13), .ShipCountry = "Germany", .ShipCity = "Frankfurt a.M.", .CustomerName = "Renate Messner"},
            New SampleOrder With {.OrderID = 10280, .OrderDate = New Date(1996, 8, 14), .ShipCountry = "Sweden", .ShipCity = "Luleå", .CustomerName = "Christina Berglund"},
            New SampleOrder With {.OrderID = 10281, .OrderDate = New Date(1996, 8, 14), .ShipCountry = "Spain", .ShipCity = "Madrid", .CustomerName = "Alejandra Camino"},
            New SampleOrder With {.OrderID = 10282, .OrderDate = New Date(1996, 8, 15), .ShipCountry = "Spain", .ShipCity = "Madrid", .CustomerName = "Alejandra Camino"},
            New SampleOrder With {.OrderID = 10283, .OrderDate = New Date(1996, 8, 16), .ShipCountry = "Venezuela", .ShipCity = "Barquisimeto", .CustomerName = "Carlos González"},
            New SampleOrder With {.OrderID = 10284, .OrderDate = New Date(1996, 8, 19), .ShipCountry = "Germany", .ShipCity = "Frankfurt a.M.", .CustomerName = "Renate Messner"},
            New SampleOrder With {.OrderID = 10285, .OrderDate = New Date(1996, 8, 20), .ShipCountry = "Germany", .ShipCity = "Cunewalde", .CustomerName = "Horst Kloss"},
            New SampleOrder With {.OrderID = 10286, .OrderDate = New Date(1996, 8, 21), .ShipCountry = "Germany", .ShipCity = "Cunewalde", .CustomerName = "Horst Kloss"},
            New SampleOrder With {.OrderID = 10287, .OrderDate = New Date(1996, 8, 22), .ShipCountry = "Brazil", .ShipCity = "Rio de Janeiro", .CustomerName = "Janete Limeira"},
            New SampleOrder With {.OrderID = 10288, .OrderDate = New Date(1996, 8, 23), .ShipCountry = "Italy", .ShipCity = "Reggio Emilia", .CustomerName = "Maurizio Moroni"},
            New SampleOrder With {.OrderID = 10289, .OrderDate = New Date(1996, 8, 26), .ShipCountry = "UK", .ShipCity = "London", .CustomerName = "Victoria Ashworth"},
            New SampleOrder With {.OrderID = 10290, .OrderDate = New Date(1996, 8, 27), .ShipCountry = "Brazil", .ShipCity = "Sao Paulo", .CustomerName = "Pedro Afonso"},
            New SampleOrder With {.OrderID = 10291, .OrderDate = New Date(1996, 8, 27), .ShipCountry = "Brazil", .ShipCity = "Rio de Janeiro", .CustomerName = "Bernardo Batista"},
            New SampleOrder With {.OrderID = 10292, .OrderDate = New Date(1996, 8, 28), .ShipCountry = "Brazil", .ShipCity = "Sao Paulo", .CustomerName = "Anabela Domingues"},
            New SampleOrder With {.OrderID = 10293, .OrderDate = New Date(1996, 8, 29), .ShipCountry = "Mexico", .ShipCity = "México D.F.", .CustomerName = "Miguel Angel Paolino"},
            New SampleOrder With {.OrderID = 10294, .OrderDate = New Date(1996, 8, 30), .ShipCountry = "USA", .ShipCity = "Albuquerque", .CustomerName = "Paula Wilson"},
            New SampleOrder With {.OrderID = 10295, .OrderDate = New Date(1996, 9, 2), .ShipCountry = "France", .ShipCity = "Reims", .CustomerName = "Paul Henriot"},
            New SampleOrder With {.OrderID = 10296, .OrderDate = New Date(1996, 9, 3), .ShipCountry = "Venezuela", .ShipCity = "Barquisimeto", .CustomerName = "Carlos González"},
            New SampleOrder With {.OrderID = 10297, .OrderDate = New Date(1996, 9, 4), .ShipCountry = "France", .ShipCity = "Strasbourg", .CustomerName = "Frédérique Citeaux"}}
    End Class
End Namespace